image: hwrunner:latest
variables:
    GIT_SSL_NO_VERIFY: "true"
    EXEC: par
    HW_DIR: hw2
    CPU_LIMIT: 60
    FILE_LIMIT: 1000000
before_script:
    - make clean all -C ${HW_DIR}
stages:
    - build
    - run
    - test
build:
    stage: build
    script:
        - echo "Build done"
run:
    stage: run
    script:
        - ulimit -t ${CPU_LIMIT}
        - ulimit -f ${FILE_LIMIT}
        - cd ${HW_DIR} && bin/${EXEC} --version

test:
    stage: test
    script:
        - ulimit -t ${CPU_LIMIT}
        - ulimit -f ${FILE_LIMIT}
        - cd ${HW_DIR} && bin/${EXEC}_tests -S --verbose=0 -j1 --timeout 30
